name: CI
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/srv.key
          chmod 600 ~/.ssh/srv.key
          cat >>~/.ssh/config <<END
          Host srv
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/srv.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Pull
        run: cd /srv/http/mbit && git pull
